#!/bin/bash

# Music player software aimed at Lindy Hop DJs.
# Copyright (C) 2024 Ghostkeeper
# This application is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This application is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for details.
# You should have received a copy of the GNU Affero General Public License along with this application. If not, see <https://gnu.org/licenses/>.

# Runs the application inside of an AppImage.

# Override some environment variables to prevent executing unsecure code.
here=$(dirname $0)
export LD_LIBRARY_PATH=$here
export PYTHONPATH=$here/lib/python3.12
export QT_PLUGIN_PATH=$here/PySide6/Qt/plugins
export QML2_IMPORT_PATH=$here/PySide6/Qt/qml

# Use XCB binaries which are packaged. E.g. Wayland is not.
export QT_QPA_PLATFORM=xcb

$here/LynDJ "$@"
